name: carousel_pro
description: A Flutter Carousel Slider widget. Support Network and Asset Images. You can modify the UI according your design easily.
version: 1.0.0
author: JLouage (Julien Louage) <info@jlouage.com>
homepage: https://github.com/jlouage/flutter-carousel-pro

#environment:
#  sdk: '>=2.0.0 <3.0.0'
#  flutter_web: ">=1.2.0 <2.0.0"

dependencies:
  flutter_web: any

dev_dependencies:
  flutter_web_test: any

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_test:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_test
